runtime: python27
# This should be 1, or we'll get error: https://cloud.google.com/appengine/docs/standard/python/config/appref
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
